### ISSUE TITLE
2.4.0 版本 导入jira插件后配置jira 账号后点击测试连接信息报错

### ISSUE THREAD

**Issue by wuyi84** [metersphere/metersphere-platform-plugin#1]
**
![image](https://user-images.githubusercontent.com/82553987/204070909-9e71a795-8397-498b-88ec-3cc987141ff2.png)
**
![image](https://user-images.githubusercontent.com/82553987/204070940-67ce0755-3b06-4b6e-b42d-ce598651dd1b.png)

**Comment by AgAngle** [comment]
你好，该项目不维护 issues，还麻烦将缺陷提交到 Metersphere 主项目下并提供下相关日志 
Mstersphere 地址：https://github.com/metersphere/metersphere/issues
日志路径：/opt/metersphere/logs/test-track/error.log
